name: ðŸš€ Deploy to EC2

on:
  push:
    branches:
      - main  # change if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ðŸ›Ž Checkout code
      uses: actions/checkout@v4

    - name: ðŸ›¡ Setup SSH
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: ðŸš€ Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/offplan_backend/offplan_backend_agent
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate --noinput
          python manage.py collectstatic --noinput
          sudo systemctl restart yourapp.service
          sudo systemctl reload nginx
        EOF
